# Generated by Django 5.1.3 on 2024-12-26 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostico', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='id_question',
            field=models.IntegerField(default=0),
        ),
    ]
